server:
  port: 8088

spring:
  application:
    name: nexus-ai-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/nexus_ai?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 1000MB      # 单个文件最大限制 (默认1MB)
      max-request-size: 1000MB   # 整个请求最大限制 (默认10MB)
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379


langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com/v1
      api-key: sk-06ed1277282342188cf2b79fab5fc00b

  deepseek:
    normal-model:
      model-name: deepseek-chat
      max-retries: 3
      timeout: 60
    reasoning-model:
      model-name: deepseek-reasoner
      max-retries: 3
      timeout: 120


nexus:
  milvus:
    host: localhost
    port: 19530
    collection-name: nexus_ai_collection
    dimension: 384

  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: nexus-files

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: nexus-group # 消费者组ID，同一组的消费者会抢任务
    auto-offset-reset: earliest # 如果没有偏移量，从头开始读
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    key-serialzer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer


